<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <PackageId>Ecommerce.Grpc.Contracts</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.3" />
    <PackageReference Include="Grpc.Core.Api" Version="2.65.0" />
    <PackageReference Include="Grpc.Tools" Version="2.65.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos\catalog.proto" GrpcServices="Both" />
    <Protobuf Include="Protos\inventory.proto" GrpcServices="Both" />
    <Protobuf Include="Protos\order.proto" GrpcServices="Both" />
    <Protobuf Include="Protos\payment.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
