apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ecommerce
data:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: https://api.tienda.example.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecommerce
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Jwt__Issuer: Ecommerce.API
  Jwt__Audience: Ecommerce.Web
  Kafka__Enabled: "false"
