apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: ecommerce
automountServiceAccountToken: false
