apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: ecommerce
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: tienda.local
      - op: replace
        path: /spec/rules/1/host
        value: api.tienda.local
      - op: remove
        path: /spec/tls
images:
  - name: ghcr.io/example/ecommerce-backend
    newName: ecommerce-backend
    newTag: local
  - name: ghcr.io/example/ecommerce-frontend
    newName: ecommerce-frontend
    newTag: local
