backend:
  replicas: 3
  image:
    repository: ghcr.io/owner/repository/backend
    tag: "1.0.0"
  autoscaling:
    minReplicas: 3
    maxReplicas: 20
frontend:
  replicas: 3
  image:
    repository: ghcr.io/owner/repository/frontend
    tag: "1.0.0"
  autoscaling:
    minReplicas: 3
    maxReplicas: 10
ingress:
  frontendHost: tienda.example.com
  backendHost: api.tienda.example.com
  tls:
    secretName: ecommerce-tls
