apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.componentName" (dict "root" . "component" "backend") }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" (dict "root" . "component" "backend" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "ecommerce.selectorLabels" (dict "root" . "component" "backend" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ecommerce.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "ecommerce.fullname" . }}-backend
            - secretRef:
                name: {{ include "ecommerce.secretName" . }}
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            {{- toYaml .Values.backend.probes.startup | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            {{- toYaml .Values.backend.probes.readiness | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            {{- toYaml .Values.backend.probes.liveness | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
