apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-backend
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.backend.config.aspnetcoreEnvironment | quote }}
  ASPNETCORE_URLS: "http://+:{{ .Values.backend.service.port }}"
  Jwt__Issuer: {{ .Values.backend.config.jwtIssuer | quote }}
  Jwt__Audience: {{ .Values.backend.config.jwtAudience | quote }}
  Kafka__Enabled: {{ .Values.backend.config.kafkaEnabled | quote }}
  Kafka__BootstrapServers: {{ .Values.kafka.bootstrapServers | quote }}
  Kafka__OrderCreatedTopic: {{ .Values.kafka.orderCreatedTopic | quote }}
  Redis__Endpoint: {{ .Values.redis.endpoint | quote }}
  Elasticsearch__Endpoint: {{ .Values.elasticsearch.endpoint | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.opentelemetry.endpoint | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-frontend
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  NODE_ENV: {{ .Values.frontend.config.nodeEnv | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.config.apiUrl | quote }}
